# Generated by Django 3.2 on 2021-05-06 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('events_board', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedPersonalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=10)),
                ('personal_description', models.TextField(default='喔喔，看來他還沒想好介紹', max_length=400)),
                ('school', models.CharField(default='國立成功大學', max_length=20)),
                ('department', models.CharField(default='電機工程學系', max_length=20)),
                ('grade', models.CharField(choices=[('freshman', '一年級'), ('sophomore', '二年級'), ('junior', '三年級'), ('senior', '四年級'), ('graduate', '研究生')], default='freshman', max_length=9)),
                ('events', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events_board.eventsboard')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('interests_tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='i-tag+', through='user_extend.TaggedInterests', to='taggit.Tag', verbose_name='Tags')),
                ('personal', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='events_board.personalboard')),
                ('personalities_tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='p-tag+', through='user_extend.TaggedPersonalities', to='taggit.Tag', verbose_name='Tags')),
                ('projects', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='events_board.projectboard')),
                ('skills_tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='s-tag+', through='user_extend.TaggedSkills', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='taggedskills',
            name='content_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='user_extend.userextend'),
        ),
        migrations.AddField(
            model_name='taggedskills',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_extend_taggedskills_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='taggedskills',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggedskills_skills', to='taggit.tag'),
        ),
        migrations.AddField(
            model_name='taggedpersonalities',
            name='content_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalities', to='user_extend.userextend'),
        ),
        migrations.AddField(
            model_name='taggedpersonalities',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_extend_taggedpersonalities_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='taggedpersonalities',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggedpersonalities_personalities', to='taggit.tag'),
        ),
        migrations.AddField(
            model_name='taggedinterests',
            name='content_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='user_extend.userextend'),
        ),
        migrations.AddField(
            model_name='taggedinterests',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_extend_taggedinterests_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='taggedinterests',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggedinterests_interests', to='taggit.tag'),
        ),
    ]
