# Generated by Django 3.2 on 2021-05-07 07:07

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('user_extend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedpersonalities',
            name='content_obj',
        ),
        migrations.RemoveField(
            model_name='taggedpersonalities',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taggedpersonalities',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='taggedskills',
            name='content_obj',
        ),
        migrations.RemoveField(
            model_name='taggedskills',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taggedskills',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='userextend',
            name='interests_tag',
        ),
        migrations.RemoveField(
            model_name='userextend',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='userextend',
            name='personalities_tag',
        ),
        migrations.RemoveField(
            model_name='userextend',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='userextend',
            name='skills_tag',
        ),
        migrations.AddField(
            model_name='userextend',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='TaggedInterests',
        ),
        migrations.DeleteModel(
            name='TaggedPersonalities',
        ),
        migrations.DeleteModel(
            name='TaggedSkills',
        ),
    ]
