# Generated by Django 3.2 on 2021-05-16 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0001_initial'),
        ('user_extend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='events',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='events_board.eventsboard'),
        ),
    ]
