# Generated by Django 3.2 on 2021-05-04 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_extend', '0002_userextend_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='department',
            field=models.CharField(default='電機工程學系', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userextend',
            name='friends',
            field=models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userextend',
            name='grade',
            field=models.CharField(choices=[('freshman', '一年級'), ('sophomore', '二年級'), ('junior', '三年級'), ('senior', '四年級'), ('graduate', '研究生')], default='freshman', max_length=9),
        ),
        migrations.AddField(
            model_name='userextend',
            name='personal_description',
            field=models.TextField(default='description', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userextend',
            name='school',
            field=models.CharField(default='國立成功大學', max_length=20),
            preserve_default=False,
        ),
    ]
