# Generated by Django 3.2 on 2021-05-31 02:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_extend', '0003_alter_userextend_personal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='unverified_friends',
            field=models.ManyToManyField(blank=True, related_name='unverified_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
