# Generated by Django 3.2 on 2021-05-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_extend', '0003_auto_20210504_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='department',
            field=models.CharField(default='電機工程學系', max_length=20),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='personal_description',
            field=models.TextField(default='喔喔，看來他還沒想好介紹', max_length=400),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='school',
            field=models.CharField(default='國立成功大學', max_length=20),
        ),
    ]
