# Generated by Django 3.2 on 2021-05-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_extend', '0004_userextend_unverified_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='img',
            field=models.ImageField(default='user/user_img_default_xanio9.png', upload_to='user/'),
        ),
    ]
