# Generated by Django 3.2 on 2021-05-04 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0006_auto_20210504_1251'),
        ('user_extend', '0004_auto_20210504_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='events',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events_board.eventsboard'),
        ),
        migrations.AddField(
            model_name='userextend',
            name='personal',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='events_board.personalboard'),
        ),
        migrations.AddField(
            model_name='userextend',
            name='projects',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='events_board.projectboard'),
        ),
    ]
