# Generated by Django 3.2 on 2021-05-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_extend', '0004_alter_userextend_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='img',
            field=models.ImageField(default='user_img_default.png', upload_to='user/'),
        ),
    ]
