# Generated by Django 3.2 on 2021-05-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0011_alter_comment_author'),
        ('user_extend', '0005_alter_userextend_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='events',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='events_board.eventsboard'),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='img',
            field=models.ImageField(default='user/user_img_default.png', upload_to='user/'),
        ),
    ]
