# Generated by Django 3.2 on 2021-05-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_extend', '0005_auto_20210504_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='full_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
