# Generated by Django 3.2 on 2021-06-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_extend', '0006_auto_20210623_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='full_name',
            field=models.CharField(default='', max_length=12),
        ),
    ]
