# Generated by Django 3.2 on 2021-05-12 15:51

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('user_extend', '0006_auto_20210508_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
