# Generated by Django 3.2 on 2021-05-04 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_extend', '0006_userextend_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
