# Generated by Django 3.2 on 2021-07-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_extend', '0008_alter_userextend_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
