# Generated by Django 3.2 on 2021-05-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
