# Generated by Django 3.2 on 2021-06-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_eventtag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventTag',
        ),
    ]
