# Generated by Django 3.2 on 2021-06-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_alter_tagcomment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tagcomment',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
