# Generated by Django 3.2 on 2021-04-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('job', models.CharField(max_length=10)),
                ('skill', models.CharField(max_length=40)),
                ('hobby', models.CharField(max_length=40)),
            ],
        ),
    ]
