# Generated by Django 3.2 on 2021-05-06 07:59

import datetime
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=70)),
                ('detail', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='events')),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('event_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=70)),
                ('detail', models.TextField()),
                ('image', models.ImageField(upload_to='personal, blank=True')),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('event_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=70)),
                ('detail', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='projects')),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('event_date', models.DateField(default=datetime.date.today)),
                ('event_tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
