# Generated by Django 3.2 on 2021-05-16 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsboard',
            name='event_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
