# Generated by Django 3.2 on 2021-05-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsboard',
            name='subtitle',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='eventsboard',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
