# Generated by Django 3.2 on 2021-05-06 07:59

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_extend', '0001_initial'),
        ('events_board', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboard',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_host_name', to='user_extend.userextend'),
        ),
        migrations.AddField(
            model_name='projectboard',
            name='interested_users',
            field=models.ManyToManyField(blank=True, related_name='project_intereted_user_name', to='user_extend.UserExtend'),
        ),
        migrations.AddField(
            model_name='projectboard',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='project_participant_name', to='user_extend.UserExtend'),
        ),
        migrations.AddField(
            model_name='personalboard',
            name='event_tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='eventsboard',
            name='event_tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='eventsboard',
            name='host',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_host_name', to='user_extend.userextend'),
        ),
        migrations.AddField(
            model_name='eventsboard',
            name='interested_users',
            field=models.ManyToManyField(blank=True, default='', related_name='event_intereted_user_name', to='user_extend.UserExtend'),
        ),
        migrations.AddField(
            model_name='eventsboard',
            name='participants',
            field=models.ManyToManyField(blank=True, default='', related_name='event_participant_name', to='user_extend.UserExtend'),
        ),
    ]
