# Generated by Django 3.2 on 2021-05-07 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='personalboard',
            name='event_tag',
        ),
        migrations.RemoveField(
            model_name='projectboard',
            name='event_tag',
        ),
        migrations.RemoveField(
            model_name='projectboard',
            name='host',
        ),
        migrations.RemoveField(
            model_name='projectboard',
            name='interested_users',
        ),
        migrations.RemoveField(
            model_name='projectboard',
            name='participants',
        ),
    ]
