# Generated by Django 3.2 on 2021-05-16 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0002_alter_eventsboard_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsboard',
            name='event_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
