# Generated by Django 3.2 on 2021-05-04 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events_board', '0003_auto_20210504_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsboard',
            name='interested_users',
            field=models.ManyToManyField(blank=True, related_name='intereted_user_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventsboard',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participant_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
