# Generated by Django 3.2 on 2021-05-07 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0003_auto_20210507_0707'),
        ('user_extend', '0002_auto_20210507_0707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalBoard',
        ),
        migrations.DeleteModel(
            name='ProjectBoard',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='user_extend.userextend'),
        ),
        migrations.AddField(
            model_name='comment',
            name='for_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events_board.eventsboard'),
        ),
    ]
