# Generated by Django 3.2 on 2021-05-04 05:39

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('events_board', '0004_auto_20210504_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsboard',
            name='event_tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
