# Generated by Django 3.2 on 2021-06-04 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_extend', '0005_alter_userextend_img'),
        ('events_board', '0004_alter_eventsboard_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='for_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to='user_extend.userextend'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='for_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to='events_board.eventsboard'),
        ),
    ]
