# Generated by Django 3.2 on 2021-05-07 07:17

from django.db import migrations
import events_board.models


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0004_auto_20210507_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=events_board.models.IntegerRangeField(default=8),
            preserve_default=False,
        ),
    ]
