# Generated by Django 3.2 on 2021-05-04 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events_board', '0005_eventsboard_event_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsboard',
            name='image',
            field=models.ImageField(blank=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='eventsboard',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_host_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventsboard',
            name='interested_users',
            field=models.ManyToManyField(blank=True, related_name='event_intereted_user_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventsboard',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='event_participant_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=70)),
                ('detail', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='projects')),
                ('event_tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_host_name', to=settings.AUTH_USER_MODEL)),
                ('interested_users', models.ManyToManyField(blank=True, related_name='project_intereted_user_name', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='project_participant_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=70)),
                ('detail', models.TextField()),
                ('image', models.ImageField(upload_to='personal, blank=True')),
                ('event_tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
