# Generated by Django 3.2 on 2021-06-04 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_extend', '0005_alter_userextend_img'),
        ('events_board', '0005_auto_20210604_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='for_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to='user_extend.userextend'),
        ),
    ]
