# Generated by Django 3.2 on 2021-05-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0005_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsboard',
            name='event_type',
            field=models.CharField(choices=[('activity', 'activity_event'), ('project', 'project_event'), ('personal', 'personal_event')], default='activity', max_length=10),
        ),
    ]
