# Generated by Django 3.2 on 2021-05-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0006_eventsboard_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsboard',
            name='event_type',
            field=models.CharField(choices=[('activity', '活動'), ('project', '專案'), ('personal', '個人專案')], default='activity', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventsboard',
            name='image',
            field=models.ImageField(blank=True, upload_to='events/'),
        ),
    ]
