# Generated by Django 3.2 on 2021-05-04 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_extend', '0008_auto_20210504_1259'),
        ('events_board', '0007_auto_20210504_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsboard',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_host_name', to='user_extend.userextend'),
        ),
        migrations.AlterField(
            model_name='eventsboard',
            name='interested_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_intereted_user_name', to='user_extend.UserExtend'),
        ),
        migrations.AlterField(
            model_name='eventsboard',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_participant_name', to='user_extend.UserExtend'),
        ),
    ]
