# Generated by Django 3.2 on 2021-06-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0007_auto_20210604_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsboard',
            name='requirements_str',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
