# Generated by Django 3.2 on 2021-05-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0007_auto_20210508_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsboard',
            name='people_wanted',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
