# Generated by Django 3.2 on 2021-06-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0008_eventsboard_requirements_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsboard',
            name='requirements',
        ),
    ]
