# Generated by Django 3.2 on 2021-05-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_extend', '0003_userextend_img'),
        ('events_board', '0008_eventsboard_people_wanted'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsboard',
            name='likes',
            field=models.ManyToManyField(related_name='event_like', to='user_extend.UserExtend'),
        ),
    ]
