# Generated by Django 3.2 on 2021-06-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0009_remove_eventsboard_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsboard',
            name='requirements_str',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
