# Generated by Django 3.2 on 2021-06-07 02:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_extend', '0005_alter_userextend_img'),
        ('events_board', '0010_alter_eventsboard_requirements_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
                ('abilities', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='user_extend.userextend')),
                ('for_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='events_board.eventsboard')),
            ],
        ),
    ]
