# Generated by Django 3.2 on 2021-05-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_extend', '0005_alter_userextend_img'),
        ('events_board', '0010_alter_eventsboard_people_wanted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='user_extend.userextend'),
        ),
    ]
