# Generated by Django 3.2 on 2021-05-05 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0010_auto_20210504_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsboard',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='eventsboard',
            name='event_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='personalboard',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='personalboard',
            name='event_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='projectboard',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='projectboard',
            name='event_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
