# Generated by Django 3.2 on 2021-05-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_extend', '0006_auto_20210508_1250'),
        ('events_board', '0011_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsboard',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='event_like', to='user_extend.UserExtend'),
        ),
    ]
