# Generated by Django 3.2 on 2021-06-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0012_apply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsboard',
            name='subtitle',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='eventsboard',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
