# Generated by Django 3.2 on 2021-05-08 17:03

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('events_board', '0012_alter_eventsboard_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsboard',
            name='event_tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
