# Generated by Django 3.2 on 2021-06-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0013_auto_20210623_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsboard',
            name='manual_closed',
            field=models.BooleanField(default=False),
        ),
    ]
