# Generated by Django 3.2 on 2021-05-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0014_alter_eventsboard_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsboard',
            name='participants',
        ),
    ]
