# Generated by Django 3.2 on 2021-06-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0014_eventsboard_manual_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmessage',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventsboard',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='eventsboard',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
