# Generated by Django 3.2 on 2021-05-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_extend', '0006_auto_20210508_1250'),
        ('events_board', '0015_remove_eventsboard_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsboard',
            name='interested_users',
        ),
        migrations.AddField(
            model_name='eventsboard',
            name='participants',
            field=models.ManyToManyField(blank=True, default='', related_name='event_participant_name', to='user_extend.UserExtend'),
        ),
    ]
