# Generated by Django 3.2 on 2021-05-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0016_auto_20210509_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsboard',
            old_name='people_wanted',
            new_name='people_limit',
        ),
    ]
