# Generated by Django 3.2 on 2021-05-12 13:58

from django.db import migrations
import events_board.models


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0017_rename_people_wanted_eventsboard_people_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsboard',
            name='people_limit',
            field=events_board.models.IntegerRangeField(),
        ),
    ]
