# Generated by Django 3.2 on 2021-05-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitenotification',
            name='notification_type',
            field=models.IntegerField(default=0),
        ),
    ]
