# Generated by Django 3.2 on 2021-05-31 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_board', '0004_alter_eventsboard_event_date'),
        ('site_notification', '0002_sitenotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitenotification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='events_board.eventsboard'),
        ),
    ]
